# Generated by Django 3.2.9 on 2021-11-29 13:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20211129_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.RenameField(
            model_name='film',
            old_name='category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='director',
            new_name='directors',
        ),
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 29, 13, 15, 45, 766873, tzinfo=utc)),
        ),
    ]
