# Generated by Django 3.2.9 on 2021-11-30 09:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_auto_20211129_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 30, 9, 0, 54, 397750, tzinfo=utc)),
        ),
    ]
