# Generated by Django 3.2.9 on 2021-12-22 08:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_alter_film_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 22, 8, 24, 11, 924374, tzinfo=utc)),
        ),
    ]
