# Generated by Django 3.2.9 on 2021-11-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='123456789', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(default='web dev', max_length=100),
            preserve_default=False,
        ),
    ]
